### ISSUE TITLE
P1AM-PROTO Gerbers ZIP file seems corrupted

### ISSUE THREAD

**Issue by Elkaid** [facts-engineering/P1AM-Design-Files#1]
I tried to download and open the ZIP file containing proto pcb gerbers but I'm getting a message "the archive is corrupt" when attempting to open it.

Also, would it be possible to provide a mechanical drawing of the board where MKR Header and Terminal Block position are shown and outer pc board dimensions.

Thanks!

**Comment by AdamCummick** [comment]
Sorry for the delayed response @Elkaid 

I tested unzipping the files on a handful of windows 10 PCs and none had any issues. What environment are you on?

Shoot me an email at adamc@facts-eng.com and I can send you the drawings.

**Comment by Elkaid** [comment]
Hello @AdamCummick , thanks for the reply.  Well, it seems to work fine this morning so I guess it might be a glitch somewhere.  Thanks for your help and happy new year :)
