### ISSUE TITLE
PGND1/2, GND?

### ISSUE THREAD

**Issue by AJ-Work-Smoothie** [facts-engineering/P1AM-Design-Files#3]
I need 24V to run my prototype module. Is there any reason to keep PGND1 & 2 isolated from GND? I cannot find continuity between the two with my DMM, so I'm just triple checking.

**Comment by AdamCummick** [comment]
PGND and GND should not typically be connected. The PGND/24V input has additional power filtering to improve noise immunity at GND. If you are not operating in a noisy environment then it probably won't be an issue to connect those grounds.
